"""user - changes user state

Revision ID: 1430e4891196
Revises: 5da636b79927
Create Date: 2022-11-15 18:07:28.525243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1430e4891196'
down_revision = '5da636b79927'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_state', sa.Enum('Enable', 'Disable', name='userstate'), server_default='Enable', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_state')
    # ### end Alembic commands ###
